name: 'Report Test Results'

on:
  workflow_run:
    workflows: ['Build and Run Tests']
    types:
      - completed

jobs:
  report-test-results:

    runs-on: ubuntu-latest

    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results-${{ github.sha }}
          name: JUnit Tests
          path: 'TEST-*.xml'
          reporter: java-junit